---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: ECR Login
      shell: "t=$(aws ecr get-login --region {{ aws_region }}) && login=${t/-e none} && $login"

#- name: Test ECR
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - aws-ecr
